language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install supercollider
script:
- mkdir -p /usr/share/SuperCollider/Extensions || true
- ln -s `pwd`/sndflo /usr/share/SuperCollider/Extensions/sndflo
- export SCFLO_TESTS_VERBOSE=1
- npm test
