language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install supercollider
script:
- export SCFLO_TESTS_VERBOSE=1
- ln -s `pwd`/sndflo ${HOME}/.local/share/SuperCollider/Extensions/sndflo
- npm test
