language: node_js
node_js:
- '0.10'
before_install:
- sudo add-apt-repository ppa:supercollider/ppa
- sudo apt-get update -qq
- sudo apt-get install supercollider
script:
- sudo mkdir -p /usr/share/SuperCollider/Extensions || true
- sudo ln -s `pwd` /usr/share/SuperCollider/Extensions/sndflo
- jackd -d dummy &
- sleep 3
- export SCFLO_TESTS_VERBOSE=1
- npm test
